image: mongo:latest

services:
  - mongo:latest

variables:
  MONGO_DB_URL: "mongodb://mongo:27017/bluefoxglovePersistence"

stages:
  - setup
  - test

setup:
  stage: setup
  script:
    - echo "Setting up the database..."
    - mongosh --eval 'db.createCollection("gameCollection")' $MONGO_DB_URL
    - mongosh --eval 'db.createCollection("playerCollection")' $MONGO_DB_URL
    - mongosh --eval 'db.createCollection("characterCollection")' $MONGO_DB_URL

test:
  stage: test
  script:
    - echo "Testing the database..."
    - mongosh --eval 'db.getCollectionNames().includes("gameCollection")' $MONGO_DB_URL
    - mongosh --eval 'db.getCollectionNames().includes("playerCollection")' $MONGO_DB_URL
    - mongosh --eval 'db.getCollectionNames().includes("characterCollection")' $MONGO_DB_URL