image: docker/compose:latest

services:
  - docker:dind

stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2

# before_script:
#   - docker info

build:
  stage: build
  image: docker
  script:
    - docker-compose build

# test:
#   stage: test
#   script:
#     - docker-compose up -d
#     - sleep 20
#     - docker-compose ps | grep bluefoxglovePersistence
#     - docker-compose down