image: docker

variables:
  DOCKER_HOST: tcp://docker:2375

services:
  - name: docker:dind
    alias: docker

stages:
  - build

build:
  stage: build
  script:
    - docker build -t bluefoxglove-mongodb .