version: '3.4'

services:
  bluefoxglovePersistence:
    container_name: bluefoxglovePersistence
    image: mongo:latest
    volumes:
        - ./mongo/data:/data/db
    ports:
        - 27017:27017
    networks:
        - bluefoxglovedemonetwork

networks:
  bluefoxglovedemonetwork:
    external: true